server:
  port: 9090

spring:
  application:
    name: event-drivent-app

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        event-consumer:
          destination: data_stream #kafka topic
          contentType: application/json
        event-producer:
          destination: data_stream
          contentType: application/json